apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: nginx
          image: registry.redhat.io/ubi8/nginx-124@sha256:9f6c14ee78e4d9229f0b91464890ebc6b381a0fbd942d92fa2fc339330b07c33
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-config
            - secretRef:
                name: demo-secret
          volumeMounts:
            - name: app-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: demo-pvc
